version: '3.8'

services:
  # --- Servicios de la API (Microservicio de Estados) ---
  # Ya no hay servicio 'postgres-db' aquí. Se conectarán a Railway.
  api-1:
    build: .
    container_name: api-1
    restart: always
    expose:
      - "3000"
    environment:
      # Docker leerá estas variables desde tu archivo .env local
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: 3000

  api-2:
    build: .
    container_name: api-2
    restart: always
    expose:
      - "3000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: 3000

  api-3:
    build: .
    container_name: api-3
    restart: always
    expose:
      - "3000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PORT: 3000

  # --- Nginx (Balanceador de carga) ---
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-1
      - api-2
      - api-3